name: p5_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0-beta.24+1
  flutter_keyboard_visibility: ^5.4.1
  flutter_code_editor: ^0.3.0
  go_router: ^10.0.0
  provider: ^6.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  sliver_tools: ^0.2.12
  path_provider: ^2.0.15
  flutter_widget_from_html: ^0.10.3
  flutter_isolate: ^2.0.4
  fk_user_agent: ^2.1.0
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  image_picker: ^1.0.2
  easy_image_viewer: ^1.2.1
  chewie: ^1.7.0
  video_player: ^2.7.0
  http: ^1.1.0

dependency_overrides:
  hive: ^3.0.0-dev
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  device_info_plus: ^9.0.3
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/p5.min.js
    - assets/p5.html
    - assets/sketch.js
    - assets/p5_examples.json
    - assets/p5_reference.json
    - assets/assets/
    - assets/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21