name: p5_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0-beta.24+1
  flutter_keyboard_visibility: ^5.4.1
  flutter_code_editor: ^0.3.0
  go_router: ^10.0.0
  provider: ^6.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  sliver_tools: ^0.2.12
  path_provider: ^2.0.15
  flutter_widget_from_html: ^0.10.3
  flutter_isolate: ^2.0.4
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev

dependency_overrides:
  hive: ^3.0.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/p5.min.js
    - assets/p5.html
    - assets/sketch.js
    - assets/p5_examples.json
    - assets/p5_reference.json
    - assets/assets/

